### PR TITLE
Update examples to use generated suitesparse-config.cmake

### PR DESCRIPTION
**Pull request by NeroBurner**
related Issues:
- https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/85
- https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/80
- https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/87#issuecomment-481974332

could someone try those examples on Windows with Visual Studio? I have tested them on Linux

Also we still need to update the README.md Section `3. Integration in your code`
https://github.com/jlblancoc/suitesparse-metis-for-windows#3-integration-in-your-code-unique-code-for-windowslinux

mabye also add a list of the available `SuiteSparse::` targets
```
	SuiteSparse::suitesparseconfig
	SuiteSparse::amd
	SuiteSparse::btf
	SuiteSparse::camd
	SuiteSparse::ccolamd
	SuiteSparse::colamd
	SuiteSparse::cholmod
	SuiteSparse::cxsparse
	SuiteSparse::klu
	SuiteSparse::ldl
	SuiteSparse::umfpack
	SuiteSparse::spqr
	SuiteSparse::metis
```

### CODE REVIEW

**Comment by jlblancoc** [comment]
Fantastic, thanks @NeroBurner ! 
I'll give it a try.

**Comment by jlblancoc** [comment]
Sorry, I could only devote a few minutes to this, here are the results:

Hmm... I'm afraid it doesn't work :-(
It seems like the generated targets does not set the target's public include directories... "cholmod.h" is not found in the example.
Checking the  "suitesparse-targets.cmake" file, I can't see any include directory property... 
But it *does* work for you, right?

BTW: 110% agreed with deleting `FindSuiteSparse.cmake`, please add it to this PR yourself. Exported targets is absolutely the way to go.

**Comment by jlblancoc** [comment]
@NeroBurner  Sorry for the radio silence, I've been totally on other projects! :-S

I just tested this again, now in Linux, and the demo projects (cholmod / spqr) correctly looks for the new CONFIG file for SP, but then fail to find `find_package(LAPACK CONFIG)` from the installed `suitesparse-config.cmake`, but it seems to me that it doesn't make sense...

Perhaps you were using HUNTER_ENABLED=ON? Because otherwise, LAPACK is found via a regular `find_package(LAPACK)` which I guess ends up using a CMake module...

What do you think?

**Comment by NeroBurner** [comment]
the generated `suitesparse-config.cmake` states, that it needs `LAPACK`, it does not specify where this dependency was found during build, because that would most probably change on another PC. 

The project using suitesparse should specify the LAPACK directory (LAPACK_DIR, where the LAPACK-config.cmake is) or also use Hunter to provide the dependencies (SuiteSparse and thus automatically LAPACK)

**Comment by NeroBurner** [comment]
@jlblancoc I updated the examples to have a `HUNTER_ENABLED` path. It worked for me on Ubuntu 18.04 and just the following packages installed by apt
```
sudo apt update && sudo apt install build-essential cmake g++ gfortran
```

for the non-Hunter way I need to think of something. Dependency management is hard because there are SO many ways to configure stuff and provide dependencies in different ways (LAPACK compiled as static or dynamic library for example). Which use cases do you think are important?

**Comment by NeroBurner** [comment]
- added a `lapack-config.cmake` file for the precompiled `lapack_windows` libraries
- updated the find_package calls to prefer to find `LAPACK` in `CONFIG` mode, and if no targets are provided continues in `MODULE` mode
- removed the automatic `lapack_windows` binary linking as it created unrelocatable installation bundles. Instead use `-DLAPACK_DIR=lapack_windows/x64` to tell cmake to use the pre compiled lapack binaries
- build the colmod and spqr example-projects on linux (gcc as well as mingw) to check if the generated `suitesparse-config.cmake` file works as intended

I've not yet updated the README with the new `LAPACK_DIR` usage

**Comment by jlblancoc** [comment]
Brilliant, thanks!! The examples work straight away (only tested with gcc)

**Pull request merged**
