### PR TITLE
GPU support in Windows

### PR DESCRIPTION
**Pull request by jhh37**
Hi there,
Firstly, thanks for maintaining this cmake repo - it's been really helpful in my domain of applications (especially with Ceres Solver)!

During my recent attempt to compile this code with CUDA support on Windows, I edited some bits that can lead to a successful build using MSVC 2015. By no means these are perfect but I was wondering if some of these may be applicable to others who want similar build conditions.

Looking forward to hearing back.

Best,
John

### CODE REVIEW

**Comment by jlblancoc** [comment]
Great! Did you finally get it working with GPU? 

I'm glad to merge; but just before that: what was your motivation to remove this one?
https://github.com/jlblancoc/suitesparse-metis-for-windows/pull/67/commits/cf2d7f580c18535d852a25ee46505a6658542a21

In theory, the "d" suffix was added to ease having both versions (Release & Debug) built and added to PATH simultaneously without problems...

**Comment by jhh37** [comment]
Hi Jose, thanks for replying back quickly.

I see, in that case I can revert the changes in "d". I had not thought about having both the debug and release versions in the installation folder. With the removal of prefix "lib", I was just trying to follow the convention of other cmake-based repos like gflags and glog and others.

Do you have a Windows+CUDA-GPU machine that you can try and compile on?

**Comment by jhh37** [comment]
There were several flaws in my original commit, so I went through and implicitly merged Andrew Mac's code. Apologies for this mistake (I didn't realize until recently that Suitesparse only supports GPU for long ints (so CHOLMOD does not use GPU acceleration in the Ceres solver).
I have checked that Andrew's test case works fine now on #67 as well, so you can probably try this also.
You can opt in for either of the pull requests I guess. #68 is good as long as it just adds some additional SPQR GPU files.
Thanks for going through the commits.

**Comment by jhh37** [comment]
@jlblancoc Hi there, just wondering how things are going with this.

**Comment by jlblancoc** [comment]
Hi! It's been **awfully** busy days... finally got to this, and merged #68. Please, give it another try and let us know if there is something else that could be improved. 

Thanks for contributing!

**Pull request closed without merging**
